matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: ruby # comes with postgres pre-installed.
      addons:
        postgresql: "9.5"
    - os: osx
      osx_image: xcode8
      before_install:
          - brew services start postgresql

before_script:
  - sudo psql -U postgres -c 'CREATE DATABASE test;'

script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
