language: generic
matrix:
  include:
    - os: osx
      osx_image: xcode8.3

before_install:
  - brew tap vapor/tap;
  - brew update;
  - brew install vapor;

install:
  - rm -rf /usr/local/var/postgres
  - initdb /usr/local/var/postgres -E utf8
  - pg_ctl -D /usr/local/var/postgres start && sleep 3 || true
  - sudo -u travis createuser -s -p 5432 postgres
  - psql -U postgres -c 'create database test;'

script:
  # run unit tests
  - swift build -Xswiftc -DNO_ANIMATION
  - swift build --configuration release -Xswiftc -DNO_ANIMATION
  - swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
