os:
  - linux
  - osx
env:
  global:
  - PGPORT=5433
  - PGHOST=localhost
language: generic
sudo: required
dist: trusty
osx_image: xcode8
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c 'create database "test";'
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"