matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services:
        - postgresql
    - os: osx
      osx_image: xcode8.3
      services:
        - postgresql
install:
  - sudo -u postgres createuser -s -p 5432 test_user &>/dev/null
  - sudo -u postgres createdb -O test -p 5432 test_user &>/dev/null
script:
  - eval "$(curl -sL https://swift.vapor.sh/ci-3.1)"
  - eval "$(curl -sL https://swift.vapor.sh/codecov)"
