language: ruby
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        postgresql: 9.5
    - os: osx
      osx_image: xcode8.3
install:
  - "[ $TRAVIS_OS_NAME = osx ] && brew services start postgresql || true"
  - psql -U postgres -c 'CREATE DATABASE test;'
script:
  - eval "$(curl -sL https://swift.vapor.sh/ci-3.1)"
  - eval "$(curl -sL https://swift.vapor.sh/codecov)"
