os:
  - linux
  - osx
env:
  global:
  - PGPORT=5432
language: generic
sudo: required
dist: trusty
osx_image: xcode8
services:
  - postgresql
addons:
  postgresql: "9.5"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
